import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0a0d14] text-white`}
      >
        <div className="bg-gradient-to-r from-red-500 via-blue-500 to-yellow-400 p-[1px]">
          <header className="bg-[#0a0d14]">
            <div className="mx-auto flex w-full max-w-6xl items-center justify-between px-6 py-3">
              <div>
                <div className="text-sm font-semibold tracking-[0.2em] text-white">POWER RANGERS</div>
                <div className="text-[10px] text-white/60">관리 시스템</div>
              </div>
              <div className="flex items-center gap-3 text-xs text-white/70">
                <span className="hidden sm:inline">레드 레인저</span>
                <span className="rounded-full bg-white/10 px-3 py-1 ring-1 ring-white/15">
                  dbase129@gmail.com
                </span>
                <button className="rounded-full bg-red-500 px-3 py-1 text-xs font-semibold text-white">
                  로그아웃
                </button>
              </div>
            </div>
          </header>
        </div>
        {children}
      </body>
    </html>
  );
}
